name: Review Demo Release Notes
permissions:
  contents: read
  actions: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CONFLUENCE_BASE_URL: "mock"
  CONFLUENCE_PAT: "mock"
  CONFLUENCE_SPACE_KEY: "mock"
  SONAR_BASE_URL: "mock"
  SONAR_PROJECT_KEY: "mock"
  SONAR_PROJECT_NAME: "mock"
  SONAR_TOKEN: "mock"

jobs:
  prepare_new_version:
    name: Prepare new version
    runs-on: ubuntu-latest

    outputs:
        finalVersion: ${{ steps.increment_tag.outputs.finalVersion }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Prepare new version
      id: increment_tag
      run: |
        set -eo pipefail
        echo "finalVersion=v0.0.10" >> $GITHUB_OUTPUT

  create_release_notes:
    name: Create Release Notes
    needs: [prepare_new_version]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Fetch all tags
      run: |
          git fetch --all

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests GitPython

    - name: Create release notes
      run: |
        set -eo pipefail
        python bin/pipeline/create_release_notes.py \
          --application 'odc' \
          --version "${{ needs.prepare_new_version.outputs.finalVersion }}"
